# Generated by Django 5.1.6 on 2025-02-23 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0002_applicant_information_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant_information',
            name='id',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
